import Head from 'next/head';
import Hero from '../components/Hero.jsx';
import Vision from '../components/Vision';
import PageMain from '../components/PageMain';
import SessionPage from '../components/SessionPage';
import AboutUs from '../components/AboutUs';
import NavBar from '../components/NavBar'
export default function Home() {
  return (
    <div className='w-full'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex flex-col w-full'>
        <Hero/>
        <Vision />
        <PageMain />
        <AboutUs />
      </div>
      
    </div>
  )
}
