import Head from 'next/head';
import Hero from '../components/Hero.jsx';
import Vision from '../components/Vision';
import PageMain from '../components/PageMain';
import AboutUs from '../components/AboutUs';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      < Hero/>
      <Vision />
      <PageMain />
      <AboutUs />
    </div>
  )
}
